Here, package.py log output is separately output to its own log file, but is **also** present in the global log.
